name: backwards_compatibility

on:
  push:

jobs:
  roave-backwards-compatibility-check:
    name: Roave Backwards Compatibility Check
    runs-on: ubuntu-latest
    continue-on-error: ${{ github.event.pull_request.base.ref != 'main' }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set safe directory
        run: git config --global --add safe.directory /github/workspace
      - name: Check for Backwards Compatibility Breaks
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"

          docker run --rm \
            -v "${GITHUB_WORKSPACE}":/github/workspace \
            -w /github/workspace \
            nyholm/roave-bc-check-ga